SELECT
  ROW_NUMBER() OVER (ORDER BY NULL) AS ID,
  PLANID,
  PLANNAME,
  M_DEPARTMENTID,
  M_DEPARTMENTNAME,
  DEPARTMENTID,
  DEPARTMENTNAME,
  ACCOUNTID,
  ACCOUNTNAME,
  SUM(DR) AS DR,
  SUM(CR) AS CR
  FROM
  (
    SELECT
      gl1.PLANID,
      pla.PLANNAME,
      mdep.DEPARTMENTID AS M_DEPARTMENTID,
      mdep.DEPARTMENTNAME AS M_DEPARTMENTNAME,
      gl1.DEPARTMENTID,
      dep.DEPARTMENTNAME,
      dep.MASTERID,
      regexp_substr(maps.M_ACCOUNT_ID,'[^|]+', 1, maps.REFLEVEL-1) ACCOUNTID,
      regexp_substr(maps.M_ACCOUNT_NAME,'[^|]+', 1, maps.REFLEVEL-1) ACCOUNTNAME,
      gl1.DR,
      gl1.CR
    FROM
     (

      SELECT gl.ACCOUNTID,gl.PLANID,gl.DEPARTMENTID,SUM(gl.DR) AS DR,SUM(gl.CR) AS CR
      FROM MASTER3D.GL gl
      LEFT JOIN MASTER3D.GLHEAD glh
      ON glh.GLHEADID = gl.GLHEADID
      WHERE GL.ACCOUNTID LIKE '5%'
      AND glh.GLHEADSTATUS != 'V'
      AND glh.GLHEADDATE >= TO_DATE('{{DATE_FRIST}}', 'DD/MM/YYYY')
      AND glh.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
      GROUP BY gl.PLANID,gl.DEPARTMENTID,gl.ACCOUNTID
    )gl1

    INNER JOIN
      (

          SELECT M_ACCOUNT_ID,M_ACCOUNT_NAME,ACCOUNTID,ACCOUNTNAME,REFLEVEL FROM
            (
              SELECT
                SYS_CONNECT_BY_PATH(ACCOUNTID,'|')   AS M_ACCOUNT_ID ,
                SYS_CONNECT_BY_PATH(ACCOUNTNAME,'|') AS M_ACCOUNT_NAME,
                ACCOUNTID,ACCOUNTNAME,MASTERID,TO_NUMBER(LEVEL) AS REFLEVEL
              FROM MASTER3D.ACCOUNT
              START WITH MASTERID        = '0'
              CONNECT BY PRIOR ACCOUNTID = MASTERID
              ORDER SIBLINGS BY ACCOUNTID
            )
          WHERE ACCOUNTID LIKE '5%'
          AND (ACCOUNTID NOT BETWEEN 5150101000 AND 5150105000)

          UNION ALL
          SELECT
            CONCAT('|5000000000|5100000000|5150000000|5150100000|5150101000|',ACCOUNTID) AS M_ACCOUNT_ID,
            CONCAT('|ค่าใช้จ่าย|ค่าใช้จ่ายจากการดำเนินงาน|ค่าเสื่อมราคาและค่าตัดจำหน่าย|ค่าเสื่อมราคา|ค่าเสื่อมราคา - อาคารและสิ่งปลูกสร้าง|',ACCOUNTNAME) AS M_ACCOUNT_NAME,
            ACCOUNTID,
            ACCOUNTNAME,
            6 AS REFLEVEL
          FROM MASTER3D.ACCOUNT
          WHERE MASTERID BETWEEN 5150101000 AND 5150104000

      )maps
      ON gl1.ACCOUNTID = maps.ACCOUNTID

      LEFT OUTER JOIN MASTER3D.DEPARTMENT dep
      ON gl1.DEPARTMENTID = dep.DEPARTMENTID

      LEFT OUTER JOIN MASTER3D.PLAN pla
      ON gl1.PLANID = pla.PLANID

      LEFT OUTER JOIN MASTER3D.DEPARTMENT mdep
      ON dep.MASTERID = mdep.DEPARTMENTID

  ) GROUP BY
    DEPARTMENTNAME,
    DEPARTMENTID,
    M_DEPARTMENTNAME,
    M_DEPARTMENTID,
    PLANNAME,
    PLANID,
    ACCOUNTNAME,
    ACCOUNTID
  ORDER BY PLANID,M_DEPARTMENTID,DEPARTMENTID,ACCOUNTID