SELECT
  ROW_NUMBER() OVER (ORDER BY GLHEAD.GLHEADDATE) AS id,
  RECEIVE.RUNNINGNUMBER,
  GL.SEQUENCE,
  GLHEAD.GLHEADDATE,
  GLHEAD.REFID1,
  GLHEAD.DESCRIPTION1,
  RECEIVE.RECEIVEFROM,
  GL.DR,
  GL.CR,
  RECEIVE.RECEIVEDATE
FROM MASTER3D.GL
INNER JOIN MASTER3D.GLHEAD
ON GLHEAD.GLHEADID = GL.GLHEADID
LEFT OUTER JOIN MASTER3D.RECEIVE
ON RECEIVE.GLHEADID        = GLHEAD.GLHEADID
WHERE ACCOUNTID = 2160001002
AND GLHEAD.GLHEADSTATUS   != 'V'
AND RECEIVE.RECEIVESTATUS != 'V'
AND (
    GLHEAD.GLHEADDATE >= TO_DATE('{{DATE_START}}', 'DD/MM/YYYY') 
    AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
)
AND (gl.DEPARTMENTID BETWEEN {{DEPARTMENT_SORCE_START}} AND {{DEPARTMENT_SORCE_END}} )
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
{{BUDGET_SQL}}

ORDER BY RECEIVE.RECEIVEDATE,
  RECEIVE.RUNNINGNUMBER,
  GL.SEQUENCE,
  GLHEAD.GLHEADDATE