SELECT 
 ROW_NUMBER() OVER (ORDER BY GLHEAD.GLHEADID) AS ID,
 RC.TRADINGNO,
 GLHEAD.DESCRIPTION1,
 RC.RECEIVEFROM,
 NVL(RCITEM.DR, 0) AS DR, NVL(RCITEM.CR, 0) AS CR,
 RC.RECEIVEDATE,
 RCITEM.CHEQUEID, RCITEM.CHEQUEDATE, 
 GLHEAD.REFID1 AS RECEIPT_NO
FROM MASTER3D.RECEIVE RC 
INNER JOIN MASTER3D.RECEIVEITEM RCITEM ON RC.RECEIVEID = RCITEM.RECEIVEID
INNER JOIN MASTER3D.RECEIVEFEE RCF ON RCF.RECEIVEFEEID = RCITEM.RECEIVEFEEID
INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = RC.GLHEADID
WHERE GLHEAD.GLHEADSTATUS != 'V'
AND RC.RECEIVESTATUS != 'V'
AND RCITEM.ACCOUNTID LIKE '2%'
AND RC.RECEIVEID = 390016
AND GLHEAD.GLHEADDATE >= TO_DATE('{{DATE_START}}', 'DD/MM/YYYY') AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (RCITEM.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
AND (RCITEM.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
AND (RCITEM.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
AND (RCITEM.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
AND (RCITEM.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )