SELECT
	*
FROM
	(
		/* Current Ratio */
		SELECT
			'1' AS ID,
			'1' AS IDG,
			'ความสามารถในการชำระหนี้' AS NAMEG,
			'อัตราส่วนทุนหมุนเวียน (Current Ratio)' AS NAME,
			(ASSET_NET / LIABILITY_NET) AS RESULT
		FROM
			(
				SELECT
					SUM (GL.DR) - SUM (GL.CR) AS ASSET_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
				WHERE
					GL.ACCOUNTID IN (
						SELECT
							ACCOUNTID
						FROM
							MASTER3D. ACCOUNT
						WHERE
							ACCOUNTSTATUS = 'Y' START WITH MASTERID = 1100000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
					)
				AND GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
			) ASSET
		CROSS JOIN (
			SELECT
				SUM (GL.CR) - SUM (GL.DR) AS LIABILITY_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 2100000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) LIABILITY
	)
UNION ALL
	(
		/* Quick Ratio */
		SELECT
			'2' AS ID,
			'1' AS IDG,
			'ความสามารถในการชำระหนี้' AS NAMEG,
			'อัตราส่วนทดสอบสภาพคล่อง (Quick Ratio)' AS NAME,
			(ASSET_NET / LIABILITY_NET) AS RESULT
		FROM
			(
				SELECT
					SUM (GL.DR) - SUM (GL.CR) AS ASSET_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
				WHERE
					GL.ACCOUNTID IN (
						SELECT
							ACCOUNTID
						FROM
							MASTER3D. ACCOUNT
						WHERE
							ACCOUNTSTATUS = 'Y' START WITH MASTERID = 1100000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
					)
				AND GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
			) ASSET
		CROSS JOIN (
			SELECT
				SUM (GL.CR) - SUM (GL.DR) AS LIABILITY_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 2100000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) LIABILITY
	)
UNION ALL
	(
		/* Debt/Equity Ratio */
		SELECT
			'3' AS ID,
			'2' AS IDG,
			'ความสามารถในการชำระหนี้ระยะยาว' AS NAMEG,
			'อัตราส่วนหนี้สินรวม ต่อ ทุน (Debt/Equity Ratio)' AS NAME,
			(LIABILITY_NET / CAPITAL_NET) AS RESULT
		FROM
			(
				SELECT
					SUM (CR) - SUM (DR) AS LIABILITY_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
				WHERE
					GL.ACCOUNTID IN (
						SELECT
							ACCOUNTID
						FROM
							MASTER3D. ACCOUNT
						WHERE
							ACCOUNTSTATUS = 'Y' START WITH MASTERID = 2000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
					)
				AND GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
			) LIABILITY
		CROSS JOIN (
			SELECT
				SUM (CR) - SUM (DR) AS CAPITAL_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
				
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 3100011000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) CAPITAL
	)
UNION ALL
	(
		/* Owner's Equity to Total Asset: OEA */
		SELECT
			'4' AS ID,
			'2' AS IDG,
			'ความสามารถในการชำระหนี้ระยะยาว' AS NAMEG,
			'อัตราส่วนของเจ้าของ ต่อสินทรัพย์รวม (Owners Equity to Total Asset)' AS NAME,
			(CAPITAL_NET / ASSET_NET) AS RESULT_OEA
		FROM
			(
				SELECT
					SUM (CR) - SUM (DR) AS CAPITAL_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
				WHERE
					GL.ACCOUNTID IN (
						SELECT
							ACCOUNTID
						FROM
							MASTER3D. ACCOUNT
						WHERE
							ACCOUNTSTATUS = 'Y' START WITH MASTERID = 3000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
					)
				AND GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
			) CAPITAL
		CROSS JOIN (
			SELECT
				SUM (DR) - SUM (CR) AS ASSET_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 1000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) ASSET
	)
UNION ALL
	(
		/* Equity to Total Asset */
		SELECT
			'5' AS ID,
			'2' AS IDG,
			'ความสามารถในการชำระหนี้ระยะยาว' AS NAMEG,
			'อัตราส่วนของทุน / สินทรัพย์รวม (Equity to Total Asset)' AS NAME,
			(CAPITAL_NET / ASSET_NET) AS RESULT_EA
		FROM
			(
				SELECT
					SUM (CR) - SUM (DR) AS CAPITAL_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
				WHERE
					GL.ACCOUNTID IN (
						SELECT
							ACCOUNTID
						FROM
							MASTER3D. ACCOUNT
						WHERE
							ACCOUNTSTATUS = 'Y' START WITH MASTERID = 3100011000 CONNECT BY PRIOR ACCOUNTID = MASTERID
					)
				AND GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
			) CAPITAL
		CROSS JOIN (
			SELECT
				SUM (DR) - SUM (CR) AS ASSET_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 1000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) ASSET
	)
UNION ALL
	(
		/* Debt to Total Asset */
		SELECT
			'6' AS ID,
			'2' AS IDG,
			'ความสามารถในการชำระหนี้ระยะยาว' AS NAMEG,
			'อัตราส่วนหนี้สินรวม ต่อ สินทรัพย์รวม (Debt to Total Asset)' AS NAME,
			(LIABILITY_NET / ASSET_NET) AS RESULT
		FROM
			(
				SELECT
					SUM (CR) - SUM (DR) AS LIABILITY_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
				WHERE
					GL.ACCOUNTID IN (
						SELECT
							ACCOUNTID
						FROM
							MASTER3D. ACCOUNT
						WHERE
							ACCOUNTSTATUS = 'Y' START WITH MASTERID = 2000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
					)
				AND GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
			) LIABILITY
		CROSS JOIN (
			SELECT
				SUM (DR) - SUM (CR) AS ASSET_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 1000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) ASSET
	)
UNION ALL
	(
		/* Net Profit Margin */
		SELECT
			'7' AS ID,
			'3' AS IDG,
			'ความสามารถในการทำกำไร' AS NAMEG,
			'อัตราส่วนกำไรสุทธิ ต่อ รายรับ (Net Profit Margin)' AS NAME,
			(REVENUE_NET - EXPENSE_NET) / REVENUE_NET * 100 AS RESULT
		FROM
			(
				SELECT
					SUM (CR) - SUM (DR) AS REVENUE_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
				WHERE
					GL.ACCOUNTID IN (
						SELECT
							ACCOUNTID
						FROM
							MASTER3D. ACCOUNT
						WHERE
							ACCOUNTSTATUS = 'Y' START WITH MASTERID = 4000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
					)
				AND GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
			) REVENUE
		CROSS JOIN (
			SELECT
				SUM (DR) - SUM (CR) AS EXPENSE_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 5000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) EXPENSE
	)
UNION ALL
	(
		/* Return on Owner's Investment: ROI */
		SELECT
			'8' AS ID,
			'3' AS IDG,
			'ความสามารถในการทำกำไร' AS NAMEG,
			'อัตราผลตอบแทนจากการลงทุนของส่วนของเจ้าของ (Return on Owners Investment)' AS NAME,
			(REVENUE_NET - EXPENSE_NET) / CAPITAL_NET * 100 AS RESULT
		FROM
			(
				SELECT
					SUM (CR) - SUM (DR) AS REVENUE_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
				WHERE
					GL.ACCOUNTID IN (
						SELECT
							ACCOUNTID
						FROM
							MASTER3D. ACCOUNT
						WHERE
							ACCOUNTSTATUS = 'Y' START WITH MASTERID = 4000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
					)
				AND GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
			) REVENUE
		CROSS JOIN (
			SELECT
				SUM (DR) - SUM (CR) AS EXPENSE_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 5000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) EXPENSE
		CROSS JOIN (
			SELECT
				SUM (CR) - SUM (DR) AS CAPITAL_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 3000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) CAPITAL
	)
UNION ALL
	(
		/* Return on Total Asset: ROA */
		SELECT
			'9' AS ID,
			'3' AS IDG,
			'ความสามารถในการทำกำไร' AS NAMEG,
			'อัตราผลตอบแทนจากสินทรัพย์รวม (Return on Total Asset)' AS NAME,
			(REVENUE_NET - EXPENSE_NET) / ASSET_NET * 100 AS RESULT
		FROM
			(
				SELECT
					SUM (CR) - SUM (DR) AS REVENUE_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
				WHERE
					GL.ACCOUNTID IN (
						SELECT
							ACCOUNTID
						FROM
							MASTER3D. ACCOUNT
						WHERE
							ACCOUNTSTATUS = 'Y' START WITH MASTERID = 4000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
					)
				AND GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
			) REVENUE
		CROSS JOIN (
			SELECT
				SUM (DR) - SUM (CR) AS EXPENSE_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 5000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')
		) EXPENSE
		CROSS JOIN (
			SELECT
				SUM (DR) - SUM (CR) AS ASSET_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ACC ON ACC.ACCOUNTID = GL.ACCOUNTID
			WHERE
				GL.ACCOUNTID IN (
					SELECT
						ACCOUNTID
					FROM
						MASTER3D. ACCOUNT
					WHERE
						ACCOUNTSTATUS = 'Y' START WITH MASTERID = 1000000000 CONNECT BY PRIOR ACCOUNTID = MASTERID
				)
			AND GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE ('{{DATE_END}}', 'DD/MM/YYYY')

		) ASSET
	)