SELECT
	*
FROM
	(
		/* Current Ratio */
		SELECT
 			'1'                                       AS id,
     		'1'                                       AS IDG,
			 'ความสามารถในการชำระหนี้'                 AS NAMEG,
     'อัตราส่วนทุนหมุนเวียน (Current Ratio)'   AS NAME,
			(ASSET_NET / LIABILITY_NET)AS RESULT
		FROM
			(
				SELECT
					SUM(GL.DR - GL.CR)AS ASSET_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
				INNER JOIN(
					SELECT
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
						ACCOUNTID AS ACCOUNT_ID,
						ACCOUNTNAME AS ACCOUNT_NAME,
						ACCOUNT_LEVEL,
						NATURETYPE
					FROM
						(
							SELECT
								ACCOUNTID,
								ACCOUNTNAME,
								LEVEL AS ACCOUNT_LEVEL,
								SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
								SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
								NATURETYPE
							FROM
								MASTER3D. ACCOUNT START WITH MASTERID = '0'
							AND ACCOUNTSTATUS = 'Y'
							AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
						)
					WHERE
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)= 1100000000
				)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
				WHERE
					GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
			)ASSET
		CROSS JOIN(
			SELECT
				SUM(GL.CR - GL.DR)AS LIABILITY_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)= 2100000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)LIABILITY
	)
UNION ALL
	(
		/* Quick Ratio */
		SELECT
			'2'                                       AS id,
     		'1'                                       AS IDG,
			  'ความสามารถในการชำระหนี้'                                      AS NAMEG,
     'อัตราส่วนทดสอบสภาพคล่อง (Quick Ratio)'                        AS NAME,
			(ASSET_NET / LIABILITY_NET)AS RESULT
		FROM
			(
				SELECT
					SUM(GL.DR - GL.CR)AS ASSET_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
				INNER JOIN(
					SELECT
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
						ACCOUNTID AS ACCOUNT_ID,
						ACCOUNTNAME AS ACCOUNT_NAME,
						ACCOUNT_LEVEL,
						NATURETYPE
					FROM
						(
							SELECT
								ACCOUNTID,
								ACCOUNTNAME,
								LEVEL AS ACCOUNT_LEVEL,
								SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
								SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
								NATURETYPE
							FROM
								MASTER3D. ACCOUNT START WITH MASTERID = '0'
							AND ACCOUNTSTATUS = 'Y'
							AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
						)
					WHERE
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)= 1100000000
				)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
				WHERE
					GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
			)ASSET
		CROSS JOIN(
			SELECT
				SUM(GL.CR - GL.DR)AS LIABILITY_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)= 2100000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)LIABILITY
	)
UNION ALL
	(
		/* Debt/Equity Ratio */
		SELECT
			'3'                                       AS id,
     		'2'                                       AS IDG,
			'ความสามารถในการชำระหนี้ระยะยาว'                  AS NAMEG,
     'อัตราส่วนหนี้สินรวม ต่อ ทุน (Debt/Equity Ratio)' AS NAME,
			(DEBT_NET / CAPITAL_NET)AS RESULT
		FROM
			(
				SELECT
					SUM(CR - DR)AS DEBT_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
				INNER JOIN(
					SELECT
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
						ACCOUNTID AS ACCOUNT_ID,
						ACCOUNTNAME AS ACCOUNT_NAME,
						ACCOUNT_LEVEL,
						NATURETYPE
					FROM
						(
							SELECT
								ACCOUNTID,
								ACCOUNTNAME,
								LEVEL AS ACCOUNT_LEVEL,
								SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
								SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
								NATURETYPE
							FROM
								MASTER3D. ACCOUNT START WITH MASTERID = '0'
							AND ACCOUNTSTATUS = 'Y'
							AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
						)
					WHERE
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 1000000000
				)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
				WHERE
					GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
			)DEBT
		CROSS JOIN(
			SELECT
				SUM(CR - DR)AS CAPITAL_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)= 3100011000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)CAPITAL
	)
UNION ALL
	(
		/* Owner's Equity to Total Asset: OEA */
		SELECT
			'4'                                       AS id,
     		'2'                                       AS IDG,
			  'ความสามารถในการชำระหนี้ระยะยาว'                                    AS NAMEG,
     'อัตราส่วนของเจ้าของ ต่อสินทรพย์รวม (Owners Equity to Total Asset)' AS NAME,
			(CAPITAL_NET / ASSET_NET)AS RESULT_OEA
		FROM
			(
				SELECT
					SUM(CR - DR)AS CAPITAL_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
				INNER JOIN(
					SELECT
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
						ACCOUNTID AS ACCOUNT_ID,
						ACCOUNTNAME AS ACCOUNT_NAME,
						ACCOUNT_LEVEL,
						NATURETYPE
					FROM
						(
							SELECT
								ACCOUNTID,
								ACCOUNTNAME,
								LEVEL AS ACCOUNT_LEVEL,
								SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
								SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
								NATURETYPE
							FROM
								MASTER3D. ACCOUNT START WITH MASTERID = '0'
							AND ACCOUNTSTATUS = 'Y'
							AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
						)
					WHERE
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)= 3100009000
				)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
				WHERE
					GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
			)CAPITAL
		CROSS JOIN(
			SELECT
				SUM(DR - CR)AS ASSET_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 1000000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)ASSET
	)
UNION ALL
	( /*NEW ADD TOPIC */
		/* Equity to Total Asset */
		SELECT
			'5'                                       AS id,
     		'2'                                       AS IDG,
			  'ความสามารถในการชำระหนี้ระยะยาว'                             AS NAMEG,
     'อัตราส่วนของทุน / สินทรัพย์รวม (Equity to Total Asset)' AS NAME,
			(LIABILITY_NET / ASSET_NET)AS RESULT
		FROM
			(
				SELECT
					SUM(CR - DR)AS LIABILITY_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
				INNER JOIN(
					SELECT
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
						ACCOUNTID AS ACCOUNT_ID,
						ACCOUNTNAME AS ACCOUNT_NAME,
						ACCOUNT_LEVEL,
						NATURETYPE
					FROM
						(
							SELECT
								ACCOUNTID,
								ACCOUNTNAME,
								LEVEL AS ACCOUNT_LEVEL,
								SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
								SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
								NATURETYPE
							FROM
								MASTER3D. ACCOUNT START WITH MASTERID = '0'
							AND ACCOUNTSTATUS = 'Y'
							AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
						)
					WHERE
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 2000000000
				)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
				WHERE
					GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
			)LIABILITY
		CROSS JOIN(
			SELECT
				SUM(DR - CR)AS ASSET_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 1000000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)ASSET
	)
UNION ALL
	(
		/* Debt to Total Asset */
		SELECT
			'6'                                       AS id,
     		'2'                                       AS IDG,
			  'ความสามารถในการชำระหนี้ระยะยาว'                             AS NAMEG,
     'อัตราส่วนหนี้สินรวม ต่อ สินทรัพย์รวม (Debt to Total Asset)' AS NAME,
			(LIABILITY_NET / ASSET_NET)AS RESULT
		FROM
			(
				SELECT
					SUM(CR - DR)AS LIABILITY_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
				INNER JOIN(
					SELECT
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
						ACCOUNTID AS ACCOUNT_ID,
						ACCOUNTNAME AS ACCOUNT_NAME,
						ACCOUNT_LEVEL,
						NATURETYPE
					FROM
						(
							SELECT
								ACCOUNTID,
								ACCOUNTNAME,
								LEVEL AS ACCOUNT_LEVEL,
								SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
								SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
								NATURETYPE
							FROM
								MASTER3D. ACCOUNT START WITH MASTERID = '0'
							AND ACCOUNTSTATUS = 'Y'
							AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
						)
					WHERE
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 2000000000
				)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
				WHERE
					GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
			)LIABILITY
		CROSS JOIN(
			SELECT
				SUM(DR - CR)AS ASSET_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 1000000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)ASSET
	)
UNION ALL
	(
		/* Net Profit Margin */
		SELECT
			'7'                                       AS id,
     		'3'                                       AS IDG,
			'ความสามารถในการทำกำไร'                                        AS NAMEG,
     'อัตราส่วนกำไรสุทธิ ต่อ รายรับ (Net Profit Margin)'            AS NAME,
			(REVENUE_NET - EXPENSE_NET)/ REVENUE_NET * 100 AS RESULT
		FROM
			(
				SELECT
					SUM(CR - DR)AS REVENUE_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
				INNER JOIN(
					SELECT
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
						ACCOUNTID AS ACCOUNT_ID,
						ACCOUNTNAME AS ACCOUNT_NAME,
						ACCOUNT_LEVEL,
						NATURETYPE
					FROM
						(
							SELECT
								ACCOUNTID,
								ACCOUNTNAME,
								LEVEL AS ACCOUNT_LEVEL,
								SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
								SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
								NATURETYPE
							FROM
								MASTER3D. ACCOUNT START WITH MASTERID = '0'
							AND ACCOUNTSTATUS = 'Y'
							AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
						)
					WHERE
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 4000000000
				)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
				WHERE
					GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
			)REVENUE
		CROSS JOIN(
			SELECT
				SUM(DR - CR)AS EXPENSE_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 5000000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)EXPENSE
	)
UNION ALL
	(
		/* Return on Owner's Investment: ROI */
		SELECT
			'8'                                       AS id,
     		'3'                                       AS IDG,
			    'ความสามารถในการทำกำไร'                                                   AS NAMEG,
     'อัตราผลตอบแทนจากการลงทุนของส่วนของเจ้าของ (Return on Owners Investment)' AS NAME,
			(REVENUE_NET - EXPENSE_NET)/ CAPITAL_NET * 100 AS RESULT
		FROM
			(
				SELECT
					SUM(CR - DR)AS REVENUE_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
				INNER JOIN(
					SELECT
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
						ACCOUNTID AS ACCOUNT_ID,
						ACCOUNTNAME AS ACCOUNT_NAME,
						ACCOUNT_LEVEL,
						NATURETYPE
					FROM
						(
							SELECT
								ACCOUNTID,
								ACCOUNTNAME,
								LEVEL AS ACCOUNT_LEVEL,
								SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
								SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
								NATURETYPE
							FROM
								MASTER3D. ACCOUNT START WITH MASTERID = '0'
							AND ACCOUNTSTATUS = 'Y'
							AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
						)
					WHERE
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 4000000000
				)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
				WHERE
					GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
			)REVENUE
		CROSS JOIN(
			SELECT
				SUM(DR - CR)AS EXPENSE_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 5000000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)EXPENSE
		CROSS JOIN(
			SELECT
				SUM(CR - DR)AS CAPITAL_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 3000000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)CAPITAL
	)
UNION ALL
	(
		/* Return on Total Asset: ROA */
		SELECT
			'9'                                       AS id,
     		'3'                                       AS IDG,
			 'ความสามารถในการทำกำไร'                                      AS NAMEG,
     'อัตราผลตอบแทนจากสินทรัพย์รวม (Return on Total Asset)'       AS NAME,
			(REVENUE_NET - EXPENSE_NET)/ ASSET_NET * 100 AS RESULT
		FROM
			(
				SELECT
					SUM(CR - DR)AS REVENUE_NET
				FROM
					MASTER3D.GL
				INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
				INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
				INNER JOIN(
					SELECT
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
						REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
						ACCOUNTID AS ACCOUNT_ID,
						ACCOUNTNAME AS ACCOUNT_NAME,
						ACCOUNT_LEVEL,
						NATURETYPE
					FROM
						(
							SELECT
								ACCOUNTID,
								ACCOUNTNAME,
								LEVEL AS ACCOUNT_LEVEL,
								SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
								SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
								NATURETYPE
							FROM
								MASTER3D. ACCOUNT START WITH MASTERID = '0'
							AND ACCOUNTSTATUS = 'Y'
							AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
						)
					WHERE
						REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 4000000000
				)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
				WHERE
					GL.GLHEADSTATUS != 'V'
				AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
			)REVENUE
		CROSS JOIN(
			SELECT
				SUM(DR - CR)AS EXPENSE_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 5000000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)EXPENSE
		CROSS JOIN(
			SELECT
				SUM(DR - CR)AS ASSET_NET
			FROM
				MASTER3D.GL
			INNER JOIN MASTER3D.GLHEAD ON GLHEAD.GLHEADID = GL.GLHEADID
			INNER JOIN MASTER3D. ACCOUNT ON ACCOUNT .ACCOUNTID = GL.ACCOUNTID
			INNER JOIN(
				SELECT
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)M_ACCOUNT_ID_1,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 1)M_ACCOUNT_NAME_1,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 2)M_ACCOUNT_ID_2,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 2)M_ACCOUNT_NAME_2,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 3)M_ACCOUNT_ID_3,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 3)M_ACCOUNT_NAME_3,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 4)M_ACCOUNT_ID_4,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 4)M_ACCOUNT_NAME_4,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 5)M_ACCOUNT_ID_5,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 5)M_ACCOUNT_NAME_5,
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 6)M_ACCOUNT_ID_6,
					REGEXP_SUBSTR(M_ACCOUNT_NAME, '[^|]+', 1, 6)M_ACCOUNT_NAME_6,
					ACCOUNTID AS ACCOUNT_ID,
					ACCOUNTNAME AS ACCOUNT_NAME,
					ACCOUNT_LEVEL,
					NATURETYPE
				FROM
					(
						SELECT
							ACCOUNTID,
							ACCOUNTNAME,
							LEVEL AS ACCOUNT_LEVEL,
							SYS_CONNECT_BY_PATH(ACCOUNTID, '|')AS M_ACCOUNT_ID,
							SYS_CONNECT_BY_PATH(ACCOUNTNAME, '|')AS M_ACCOUNT_NAME,
							NATURETYPE
						FROM
							MASTER3D. ACCOUNT START WITH MASTERID = '0'
						AND ACCOUNTSTATUS = 'Y'
						AND CUTOFFTYPE IS NOT NULL CONNECT BY PRIOR ACCOUNTID = MASTERID ORDER SIBLINGS BY ACCOUNTID
					)
				WHERE
					REGEXP_SUBSTR(M_ACCOUNT_ID, '[^|]+', 1, 1)= 1000000000
			)TMP ON TMP.ACCOUNT_ID = GL.ACCOUNTID
			WHERE
				GL.GLHEADSTATUS != 'V'
			AND GLHEAD.GLHEADDATE <= TO_DATE('{{DATE_END}}', 'DD/MM/YYYY')
		AND (gl.BUDGETGROUPID BETWEEN {{BUDGET_SORCE_START}} AND {{BUDGET_SORCE_END}} )
     AND (gl.PLANID BETWEEN {{PLAN_SORCE_START}} AND {{PLAN_SORCE_END}} )
     AND (gl.PROJECTID BETWEEN {{PROJECT_SORCE_START}} AND {{PROJECT_SORCE_END}} )
     AND (gl.ACTIVITYID BETWEEN {{ACTIVITY_SORCE_START}} AND {{ACTIVITY_SORCE_END}} )
     AND (gl.FUNDGROUPID BETWEEN {{FUND_SORCE_START}} AND {{FUND_SORCE_END}} )
     {{BUDGET_SQL}}
		)ASSET
	)