SELECT ROW_NUMBER() OVER (ORDER BY budget.BUDGETSOURCE) AS budgetGroupId,budget.BUDGETSOURCE AS budgetSource FROM MASTER3D.BUDGETGROUP budget
INNER JOIN (
  SELECT gl.BUDGETGROUPID
  FROM MASTER3D.GL gl
  LEFT JOIN MASTER3D.GLHEAD glh
  ON gl.GLHEADID = glh.GLHEADID
  WHERE %s
  AND glh.GLHEADSTATUS != 'v'
  GROUP BY gl.BUDGETGROUPID
) tbudget
on budget.BUDGETGROUPID = tbudget.BUDGETGROUPID
GROUP BY budget.BUDGETSOURCE
ORDER BY budget.BUDGETSOURCE