SELECT projects.PROJECTID AS projectId,projects.PROJECTNAME AS projectName FROM MASTER3D.PROJECT projects
INNER JOIN (
  SELECT gl.PROJECTID
  FROM MASTER3D.GL gl
  LEFT JOIN MASTER3D.GLHEAD glh
  ON gl.GLHEADID = glh.GLHEADID
  WHERE %s
  AND glh.GLHEADSTATUS != 'v'
  GROUP BY gl.PROJECTID
) tprojects
on projects.PROJECTID = tprojects.PROJECTID
ORDER BY projects.PROJECTID
