SELECT acco.ACCOUNTID AS accountId,acco.ACCOUNTNAME AS accountName FROM MASTER3D.ACCOUNT acco
RIGHT OUTER JOIN
(
  SELECT gl.ACCOUNTID
  FROM MASTER3D.GL gl
  LEFT JOIN MASTER3D.GLHEAD glh
  ON gl.GLHEADID = glh.GLHEADID
  AND glh.GLHEADSTATUS != 'V'
  GROUP BY ACCOUNTID
) gl
ON acco.ACCOUNTID=gl.ACCOUNTID
ORDER BY acco.ACCOUNTID
