SELECT activity.ACTIVITYID AS activityId,activity.ACTIVITYNAME AS activityName FROM MASTER3D.ACTIVITY activity
INNER JOIN (
  SELECT gl.ACTIVITYID
  FROM MASTER3D.GL gl
  LEFT JOIN MASTER3D.GLHEAD glh
  ON gl.GLHEADID = glh.GLHEADID
  WHERE %s
  AND glh.GLHEADSTATUS != 'v'
  GROUP BY gl.ACTIVITYID
) tactivity
on activity.ACTIVITYID = tactivity.ACTIVITYID
GROUP BY activity.ACTIVITYNAME,activity.ACTIVITYID
ORDER BY activity.ACTIVITYID
