SELECT plans.PLANID AS planId,plans.PLANNAME AS planName FROM MASTER3D.PLAN plans
INNER JOIN (
  SELECT gl.PLANID
  FROM MASTER3D.GL gl
  LEFT JOIN MASTER3D.GLHEAD glh
  ON gl.GLHEADID = glh.GLHEADID
  AND glh.GLHEADSTATUS != 'v'
  GROUP BY gl.PLANID
) tplans
on plans.PLANID = tplans.PLANID
ORDER BY plans.PLANID